---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-subscribe-ansible"
      label: "Subscribe Ansible"
      solveButton: false
    - name: "02-create-audit"
      label: "Create Audit"
      solveButton: false
    - name: "03-httpd-permission"
      label: "httpd-permission"
      solveButton: false
    - name: "04-selinux"
      label: "Selinux"
      solveButton: false
    - name: "05-auditd"
      label: "Auditd"
      solveButton: false
    - name: "06-fapolicyd"
      label: "Fapolicyd"
      solveButton: false
    - name: "07-bsa-playbook"
      label: "Bsa Playbook"
      solveButton: false

tabs:
  - name: ">_ terminal"
    url: /wetty_rhel/ssh/root
